extends: ../base.yaml

dataset:
  base_path: "${DATASET}/Synthetic"
  stats:
    - location
    - pose
    - pose-location
    - outfit
    - accessories
    - bodyState
    - mood
    - character
    - fixtures
    - items
  train_template: "{stat}.train.jsonl"
  eval_template: "{stat}.eval.jsonl"

model:
  model_name: "${STAGE0_BEST}"

peft:
  r: 64
  lora_alpha: rank
  lora_dropout: 0.0
  modules_to_save:
    - embed_tokens
    - lm_head
  modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj

layerwise_lr:
  base_lr: 3.0e-5
  groups:
    - name: embed
      suffixes: ["embed_tokens", "lm_head"]
      lr_scale: 0.01
      force_require_grad: true
    - name: mlp
      suffixes: ["mlp.up_proj", "mlp.gate_proj", "mlp.down_proj"]
      layers: { start: 0, end: 40 }
      lr_scale: 0.33
      force_require_grad: true
    - name: layernorms
      suffixes: ["input_layernorm"]
      layers: { start: 0, end: 40 }
      lr_scale: 0.16
      force_enable: false
      force_require_grad: true

training:
  output_dir: "${WORK_BASE}/g2b-stage1"
  #merge_output_dir: "${ARTIFACTORY_BASE}/g2b-stage1"
  merge_output_dir: null
  effective_batch_size: 12
  gradient_accumulation_steps: 1
  warmup_ratio: 0.2
  lr_scheduler_type: constant
  lr_scheduler_kwargs:
    min_lr_rate: 0.2
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.99
  max_steps: 1200
  logging_steps: 1
  save_strategy: steps
  save_steps: 1200
  save_only_model: false
  eval_strategy: steps
  eval_steps: 50
  eval_on_start: true

  max_grad_norm: 1.0
  max_grad_norm_schedule:
    type: linear
    args:
      start_value: 0.1
      end_value: 1.0
      start_step: 0.0
      end_step: 0.2

loss:
  use_fork_weighed: true
  fork_mask_key: fork_mask
  fork_alpha: 1.0
  fork_alpha_schedule:
    type: cosine
    args:
      start_rate: 0 # ratio of alpha
      end_rate: 1.0
      start_step: 0.2 # ratio of total steps
      end_step: 0.8
  mask_generator:
    type: after_special_token
    args:
      tokens: ["=\"", ",", " (", ";"]
      include_special_tokens: true

gradient_logging:
  enabled: true