name: pod
vars:
  ARTIFACTORY_BASE: "/workspace/artifacts"
  DATASET_BASE: "/workspace/datasets"
  LOGS_BASE: "/mnt/logs/pipeline_runs"
  CONFIG_BASE: "/workspace/configs"
  WORK_BASE: "/mnt/work/in_training"
