name: pod
vars:
  ARTIFACTORY_BASE: "/workspace/artifacts"
  DATASET_BASE: "/workspace/datasets"
  LOGS_BASE: "/workspace/work/logs/"
  CONFIG_BASE: "/workspace/configs"
  WORK_BASE: "/workspace/work/in_training"
