name: pod
vars:
  ARTIFACTORY_BASE: "/workspace/artifacts"
  DATASET_BASE: "/workspace/Dataset"
  LOGS_BASE: "/workspace/work/logs/"
  CONFIG_BASE: "./configs"
  WORK_BASE: "/workspace/work/in_training"
