environment: configs/environments/local.yaml
vars:
  MODEL_NAME: "g2b"
  DATASET: "${DATASET_BASE}_prepared/${MODEL_NAME}"

stages:
  - name: pull_stage1_from_hf
    pull_from_hf:
      model_id: LeDissolution/statsuite_stage0
      output_dir: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage0
      var_name: STAGE1_BEST

  - name: stage2_make_sweeps
    make_sweeps:
      base_config: configs/granite2b/stage2/base.yaml
      name: seeds
      param_ranges:
        peft.random_state: [42, 1234, 3407]

  - name: stage2
    env_variables:
      - name: CUDA_VISIBLE_DEVICES
        value: "1"
      - name: PER_EX_TRAIN_LOG_TOPK
        value: "5"
      - name: PER_EX_TRAIN_LOG_MIN_LOSS
        value: "0.5"
      - name: PER_EX_TRAIN_LOG_TEXT
        value: "1"
    script:
      name: train.py
      args:
        --config: #${CONFIG_BASE}/granite2b/stage2/base.yaml
          sweep: configs/granite2b/stage2/seeds

  - name: pick_best_stage2
    select_best:
      from_dir: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage2
      metric: exact_match
      prefer: max
      file: last_eval_metrics.json
      var_name: STAGE2_BEST
      fallback: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage2