environment: configs/environments/pod.yaml
vars:
  MODEL_NAME: "g2b"
  DATASET: "${DATASET_BASE}_prepared/${MODEL_NAME}"

stages:
  - name: pick_best_stage2
    select_best:
      from_dir: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage2
      metric: exact_match
      prefer: max
      file: last_eval_metrics.json
      var_name: STAGE2_BEST
      fallback: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage2

  - name: prepare_dataset
    script:
      name: ../DatasetProcessor/prepare_dataset.py
      venv: ../DatasetProcessor/.venv
      args:
        --base_path: "${DATASET_BASE}"
        --out_path: "${DATASET}_post"
        --with_loss: true
        --with_chats: true
        --with_synthetic: true
        --clean: true
        --model_name: "${STAGE2_BEST}"
        --devices: "0"

  - name: assemble_dataset
    script:
      name: ../DatasetProcessor/assemble_dataset.py
      venv: ../DatasetProcessor/.venv
      args:
        --base_path: "${DATASET}_post"