environment: configs/environments/pod.yaml
vars:
  MODEL_NAME: "g2b"
  DATASET: "${DATASET_BASE}_prepared/${MODEL_NAME}"

stages:
  - name: prepare_dataset
    script:
      name: ../DatasetProcessor/prepare_dataset.py
      venv: ../DatasetProcessor/.venv
      args:
        --base_path: "${DATASET_BASE}"
        --out_path: "${DATASET}"
        --with_loss: false
        --with_chats: false
        --with_synthetic: true
        --clean: true

  - name: pull_stage0_from_hf
    pull_from_hf:
      model_id: LeDissolution/statsuite_stage0
      output_dir: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage0
      var_name: STAGE0_BEST

  - name: stage1_make_sweeps
    make_sweeps:
      base_config: configs/granite2b/stage1/base.yaml
      name: gate_lr
      param_ranges:
        peft.random_state: [42, 1234, 3407, 5678, 9999, 10000]
        training.max_grad_norm_schedule: ["linear"]
        training.max_grad_norm_schedule.args.start_value: [0.01, 0.1]

  - name: stage1
    env_variables:
      - name: CUDA_VISIBLE_DEVICES
        value: 0
      - name: PER_EX_TRAIN_LOG_TOPK
        value: "5"
      - name: PER_EX_TRAIN_LOG_MIN_LOSS
        value: "0.5"
      - name: PER_EX_TRAIN_LOG_TEXT
        value: "1"
    script:
      name: train.py
      args:
        --config:
          sweep: ${CONFIG_BASE}/granite2b/stage1/gate_lr

  # - name: stage2
  #   env_variables:
  #     - name: CUDA_VISIBLE_DEVICES
  #       value: 1
  #   script:
  #     name: train.py
  #     args:
  #       --config: ${CONFIG_BASE}/granite2b/stage2/base.yaml