environment: configs/environments/pod.yaml
vars:
  MODEL_NAME: "qwen0.6b"
  DATASET: "${DATASET_BASE}_prepared/${MODEL_NAME}"

stages:
  - name: pull_stage1_from_hf
    pull_from_hf:
      model_id: LeDissolution/statsuite_qwen0.6b_stage0
      output_dir: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage0
      var_name: STAGE1_BEST

  - name: prepare_dataset
    script:
      name: ../DatasetProcessor/prepare_dataset.py
      venv: ../DatasetProcessor/.venv
      args:
        --base_path: "${DATASET_BASE}"
        --out_path: "${DATASET}"
        --with_loss: true
        --with_chats: true
        --with_synthetic: true
        --clean: false
        --model_name: "${STAGE1_BEST}"
        --devices: "0,1,2,3"

  - name: assemble_dataset
    script:
      name: ../DatasetProcessor/assemble_dataset.py
      venv: ../DatasetProcessor/.venv
      args:
        --base_path: "${DATASET}"
        --existing_eval_file: "${DATASET}/Assembled/eval.jsonl"
        --batch_size: 24
        --epochs: 2

  - name: stage2_make_sweeps
    make_sweeps:
      base_config: configs/qwen0.6b/stage2/base.yaml
      name: seeds
      param_ranges:
        training.dataset_seed: [42, 1234, 3407]
        training.max_steps: [3000]
        training.warmup_ratio: [0.03]
        training.disable_shuffle: [false]
        training.batch_shuffle: [true]
        
  - name: stage2
    env_variables:
      - name: CUDA_VISIBLE_DEVICES
        value: 0
      - name: PER_EX_TRAIN_LOG_TOPK
        value: "5"
      - name: PER_EX_TRAIN_LOG_MIN_LOSS
        value: "0.5"
      - name: PER_EX_TRAIN_LOG_TEXT
        value: "1"
    script:
      name: train.py
      args:
        --config: #${CONFIG_BASE}/qwen0.6b/stage2/base.yaml
          sweep: configs/qwen0.6b/stage2/seeds

  - name: pick_best_stage2
    select_best:
      from_dir: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage2
      metric: exact_match
      prefer: max
      file: last_eval_metrics.json
      var_name: STAGE2_BEST
      fallback: ${ARTIFACTORY_BASE}/${MODEL_NAME}-stage2

  - name: publish_stage2_to_hf
    publish_to_hf:
      model_id: LeDissolution/statsuite_qwen0.6b_stage2
      from_dir: ${STAGE2_BEST}

  - name: prepare_dataset_post
    script:
      name: ../DatasetProcessor/prepare_dataset.py
      venv: ../DatasetProcessor/.venv
      args:
        --base_path: "${DATASET_BASE}"
        --out_path: "${DATASET}_post"
        --with_loss: true
        --with_chats: true
        --with_synthetic: true
        --clean: true
        --model_name: "${STAGE2_BEST}"
        --devices: "0,1,2,3"

  - name: shutdown
    script:
      name: shutdown.py
